In [1]:
import numpy as np
import modern_robotics as mr
np.set_printoptions(suppress=True)


In [2]:
# Function to calculate the Jacobian
def compute_jacobian(theta, L1, L2, L3, L4):
    # Calculate the sine and cosine of the sum of the angles
    S234 = np.sin(theta[1] + theta[2] + theta[3])
    S34 = np.sin(theta[2] + theta[3])
    S23 = np.sin(theta[1] + theta[2])
    S4 = np.sin(theta[3])
    C234 = np.cos(theta[1] + theta[2] + theta[3])
    C34 = np.cos(theta[2] + theta[3])
    C23 = np.cos(theta[1] + theta[2])
    C4 = np.cos(theta[3])

    # Create the Jacobian matrix
    J = np.array([[1, 1, 1, 1],
                  [L3*S4 + L2*S34 + L1*S234, L3*S4 + L2*S34, L3*S4, 0],
                  [L4 + L3*C4 + L2*C34 + L1*C234, L4 + L3*C4 + L2*C34, L4 + L3*C4, L4]])
    return J

# Example usage:
# Define the angles in radians
theta = np.radians([0, 0, 90, -90])  # Convert degrees to radians for example purposes

# Define the lengths
L1, L2, L3, L4 = 1, 1, 1, 1  # Example lengths

# Compute the Jacobian
J = compute_jacobian(theta, L1, L2, L3, L4)
J

array([[ 1.,  1.,  1.,  1.],
       [-1., -1., -1.,  0.],
       [ 3.,  2.,  1.,  1.]])

In [8]:
# Space Jacobian from Spatial Screw Axes

S1 = np.array([0, 0, 1, 0, 0, 0])
S2 = np.array([1, 0, 0, 0, 2, 0])
S3 = np.array([0, 0, 0, 0, 1, 0])

S_list = np.column_stack((S1, S2, S3))
theta_list = np.array([np.pi/2, np.pi/2, 1])

mr.JacobianSpace(S_list, theta_list)

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0., -2., -0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  1.]])

In [9]:
# Body Jacobian from Body Screw Axes

B1 = np.array([0, 1, 0, 3, 0, 0])
B2 = np.array([-1, 0, 0, 0, 3, 0])
B3 = np.array([0, 0, 0, 0, 0, 1])

B_list = np.column_stack((B1, B2, B3))

mr.JacobianBody(B_list, theta_list)

array([[ 0., -1.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  4.,  0.],
       [ 0.,  0.,  1.]])

In [5]:
# Principal Semi-Axes of linear velocity manipulability ellipsoid

J_b = np.array([
    [0,     -1,    0,     0,    -1,     0,     0],
    [0,      0,    1,     0,     0,     1,     0],
    [1,      0,    0,     1,     0,     0,     1],
    [-0.105, 0,    0.006,-0.045, 0,     0.006, 0],
    [-0.889, 0.006,0,    -0.844, 0.006, 0,     0],
    [0,     -0.105,0.889, 0,     0,     0,     0]
])

J_b_v = J_b[3:, :] # Longest
J_b_v

array([[-0.105,  0.   ,  0.006, -0.045,  0.   ,  0.006,  0.   ],
       [-0.889,  0.006,  0.   , -0.844,  0.006,  0.   ,  0.   ],
       [ 0.   , -0.105,  0.889,  0.   ,  0.   ,  0.   ,  0.   ]])

In [6]:
A = np.dot(J_b_v, J_b_v.T)
# Eigenvectors
_, eigenvectors = np.linalg.eig(A)

# Never output in scientific notation
np.set_printoptions(suppress=True)
eigenvectors[:, 1]

array([ 0.08715237,  0.99619497, -0.00022828])

In [7]:
np.sqrt(max(_))

1.2305357147842984