In [19]:
import numpy as np
import modern_robotics as mr

In [20]:
q = np.array([0, 0, -0.1])

In [21]:
m_qqT = np.dot(np.matmul(q.T, q), np.eye(3)) - np.matmul(q, q.T) * 187.658
m_qqT

array([[-1.8666, -1.8766, -1.8766],
       [-1.8766, -1.8666, -1.8766],
       [-1.8766, -1.8766, -1.8666]])

In [22]:
I_s = np.diag([0.3753, 0.3753, 0.3753])
I_s

array([[0.3753, 0.    , 0.    ],
       [0.    , 0.3753, 0.    ],
       [0.    , 0.    , 0.3753]])

In [23]:
I_s + m_qqT

array([[-1.4913, -1.8766, -1.8766],
       [-1.8766, -1.4913, -1.8766],
       [-1.8766, -1.8766, -1.4913]])

In [24]:
I_c = np.diag([0.005254, 0.005254, 0.001126])
I_c

array([[0.0053, 0.    , 0.    ],
       [0.    , 0.0053, 0.    ],
       [0.    , 0.    , 0.0011]])

In [25]:
I_c + 2*(I_s + m_qqT)

array([[-2.9773, -3.7532, -3.7532],
       [-3.7532, -2.9773, -3.7532],
       [-3.7532, -3.7532, -2.9814]])

In [26]:
M01 = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0.089159], [0, 0, 0, 1]]
M12 = [[0, 0, 1, 0.28], [0, 1, 0, 0.13585], [-1, 0, 0, 0], [0, 0, 0, 1]]
M23 = [[1, 0, 0, 0], [0, 1, 0, -0.1197], [0, 0, 1, 0.395], [0, 0, 0, 1]]
M34 = [[0, 0, 1, 0], [0, 1, 0, 0], [-1, 0, 0, 0.14225], [0, 0, 0, 1]]
M45 = [[1, 0, 0, 0], [0, 1, 0, 0.093], [0, 0, 1, 0], [0, 0, 0, 1]]
M56 = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0.09465], [0, 0, 0, 1]]
M67 = [[1, 0, 0, 0], [0, 0, 1, 0.0823], [0, -1, 0, 0], [0, 0, 0, 1]]
G1 = np.diag([0.010267495893, 0.010267495893,  0.00666, 3.7, 3.7, 3.7])
G2 = np.diag([0.22689067591, 0.22689067591, 0.0151074, 8.393, 8.393, 8.393])
G3 = np.diag([0.049443313556, 0.049443313556, 0.004095, 2.275, 2.275, 2.275])
G4 = np.diag([0.111172755531, 0.111172755531, 0.21942, 1.219, 1.219, 1.219])
G5 = np.diag([0.111172755531, 0.111172755531, 0.21942, 1.219, 1.219, 1.219])
G6 = np.diag([0.0171364731454, 0.0171364731454, 0.033822, 0.1879, 0.1879, 0.1879])
Glist = [G1, G2, G3, G4, G5, G6]
Mlist = [M01, M12, M23, M34, M45, M56, M67] 
Slist = [[0,         0,         0,         0,        0,        0],
         [0,         1,         1,         1,        0,        1],
         [1,         0,         0,         0,       -1,        0],
         [0, -0.089159, -0.089159, -0.089159, -0.10915, 0.005491],
         [0,         0,         0,         0,  0.81725,        0],
         [0,         0,     0.425,   0.81725,        0,  0.81725]]

theta_list = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2, 2*np.pi/3])
dtheta_list = np.array([0.2, 0.2, 0.2, 0.2, 0.2, 0.2])
ddtheta_list = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])
g = np.array([0, 0, -9.81])
F_tip = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

torq_list = mr.InverseDynamics(theta_list, dtheta_list, ddtheta_list, g, F_tip, Mlist, Glist, Slist)

In [27]:
np.set_printoptions(suppress = True, precision=4)
torq_list

array([  0.0128, -41.1477,  -3.7809,   0.0323,   0.037 ,   0.1034])