In [1]:
import numpy as np
import modern_robotics as mr

In [36]:
# Create 4x4 array
T_sa = np.array([[0, -1, 0, 0],
                [0, 0, -1, 0],
                [1, 0, 0, 1],
                [0, 0, 0, 1]])

T_as = mr.TransInv(T_sa)
AdT_as = mr.Adjoint(T_as)

Vs = np.array([[3, 2, 1, -1, -2, -3]]).T


Va = AdT_as @ Vs
Va

array([[ 1.],
       [-3.],
       [-2.],
       [-3.],
       [-1.],
       [ 5.]])

In [4]:
mat_T_sa = mr.MatrixLog6(T_sa)
mat_T_sa

array([[ 0.        , -1.20919958, -1.20919958,  0.73639986],
       [ 1.20919958,  0.        , -1.20919958,  0.47279972],
       [ 1.20919958,  1.20919958,  0.        ,  0.73639986],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [5]:
V = mr.se3ToVec(mat_T_sa)
[S, theta] = mr.AxisAng6(V)
theta

2.0943951023931957

In [37]:
S_theta = np.array([[0, 1, 2, 3, 0, 0]]).T
se3mat = mr.VecTose3(S_theta)
# Convert dtype 'object' to 'float64' upto 2 decimals
se3mat.astype('float64')

c:\Users\Winner Brixman\AppData\Local\Programs\Python\Python310\lib\site-packages\modern_robotics\core.py:88: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array([[0,      -omg[2],  omg[1]],


array([[ 0., -2.,  1.,  3.],
       [ 2.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [41]:
# Raise exponential to a matrix
mr.MatrixExp6(se3mat).astype('float64')

array([[-0.61727288, -0.70368982,  0.35184491,  1.05553472],
       [ 0.70368982, -0.2938183 ,  0.64690915,  1.94072745],
       [-0.35184491,  0.64690915,  0.67654542, -0.97036373],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [18]:
Fb = np.array([[1, 0, 0, 2, 1, 0]]).T
T_sb = np.array([[1, 0, 0, 0],
                 [0, 0, 1, 2],
                [0, -1, 0, 0],
                [0, 0, 0, 1]])

Ad_t_bs = mr.Adjoint(mr.TransInv(T_sb))
Fs = Ad_t_bs.T @ Fb
Fs

array([[-1.],
       [ 0.],
       [-4.],
       [ 2.],
       [ 0.],
       [-1.]])

In [19]:
T = np.array([[0, -1, 0, 3],
                 [1, 0, 0, 0],
                [0, 0, 1, 1],
                [0, 0, 0, 1]])
mr.TransInv(T)

array([[ 0,  1,  0,  0],
       [-1,  0,  0,  3],
       [ 0,  0,  1, -1],
       [ 0,  0,  0,  1]])

In [26]:
V = np.array([[1, 0, 0, 0, 2, 3]]).T
mr.VecTose3(V).astype(np.integer)

c:\Users\Winner Brixman\AppData\Local\Programs\Python\Python310\lib\site-packages\modern_robotics\core.py:88: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array([[0,      -omg[2],  omg[1]],
C:\Users\Winner Brixman\AppData\Local\Temp\ipykernel_17340\845240614.py:2: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
  mr.VecTose3(V).astype(np.integer)


array([[ 0,  0,  0,  0],
       [ 0,  0, -1,  2],
       [ 0,  1,  0,  3],
       [ 0,  0,  0,  0]])

In [27]:
# Q 13

s = np.array([[1, 0, 0]])
p = np.array([[0, 0, 2]])
h = 1

mr.ScrewToAxis(p, s, h)

array([[1, 0, 0],
       [1, 2, 0]])

In [49]:
# Q 14

s_theta = np.array([[0, -1.5708, 0, 2.3562],
                     [1.5708, 0, 0, -2.3562],
                     [0, 0, 0, 1],
                     [0, 0, 0, 0]])

mr.MatrixExp6(s_theta).astype(np.integer)

C:\Users\Winner Brixman\AppData\Local\Temp\ipykernel_17340\3769095143.py:8: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
  mr.MatrixExp6(s_theta).astype(np.integer)


array([[0, 0, 0, 3],
       [0, 0, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 0, 1]])

In [46]:
# Q 15
T = np.array([[0, -1, 0, 3],
              [1, 0, 0, 0],
              [0, 0, 1, 1],
              [0, 0, 0, 1]])

mr.MatrixLog6(T).astype(np.float64)

array([[ 0.        , -1.57079633,  0.        ,  2.35619449],
       [ 1.57079633,  0.        ,  0.        , -2.35619449],
       [ 0.        ,  0.        ,  0.        ,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])