In [2]:
import numpy as np
import modern_robotics as mr

In [3]:
vec = np.array([1, 2, 0.5])
mr.VecToso3(vec)

array([[ 0. , -0.5,  2. ],
       [ 0.5,  0. , -1. ],
       [-2. ,  1. ,  0. ]])

In [4]:
exp_mat = np.array([[0, 0.5, -1],[-0.5, 0, 2],[1, -2, 0]])
mr.MatrixExp3(exp_mat)

array([[ 0.60482045,  0.796274  , -0.01182979],
       [ 0.46830057, -0.34361048,  0.81401868],
       [ 0.64411707, -0.49787504, -0.58071821]])

In [6]:
R = np.array([[0,0,1],[-1,0,0],[0, -1, 0]])
ans = mr.MatrixLog3(R)
# print ans upto 3 decimal places
print(np.around(ans, decimals=3))

[[ 0.     1.209  1.209]
 [-1.209  0.     1.209]
 [-1.209 -1.209  0.   ]]


In [9]:
omg = np.array([1, 2, 0])
ans = mr.MatrixExp3(mr.VecToso3(omg))
print(np.around(ans, decimals=3))

[[-0.294  0.647  0.704]
 [ 0.647  0.677 -0.352]
 [-0.704  0.352 -0.617]]
